ALTER TABLE users ADD COLUMN role TEXT NOT NULL DEFAULT 'admin';
ALTER TABLE users ADD COLUMN allow_explicit INTEGER NOT NULL DEFAULT 0;

ALTER TABLE manga ADD COLUMN is_explicit INTEGER NOT NULL DEFAULT 0;
