// <auto-generated />
using System;
using ArrghServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArrghServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ArrghServer.Data.Models.Chapter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ChapterFormat")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("chapter_format");

                    b.Property<string>("ChapterTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("Downloaded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("downloaded");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_new");

                    b.Property<string>("LocalPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("local_path");

                    b.Property<double>("Number")
                        .HasColumnType("REAL")
                        .HasColumnName("number");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("page_count");

                    b.Property<string>("TitleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title_id");

                    b.Property<double?>("Volume")
                        .HasColumnType("REAL")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("idx_chapters_title_id");

                    b.ToTable("chapters", (string)null);
                });

            modelBuilder.Entity("ArrghServer.Data.Models.ChapterSource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ChapterId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("chapter_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("idx_chapter_sources_chapter_id");

                    b.HasIndex("ChapterId", "Source")
                        .IsUnique();

                    b.ToTable("chapter_sources", (string)null);
                });

            modelBuilder.Entity("ArrghServer.Data.Models.DownloadQueueItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ChapterId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("chapter_id");

                    b.Property<double>("ChapterNum")
                        .HasColumnType("REAL")
                        .HasColumnName("chapter_num");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<string>("MangaTitle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manga_title");

                    b.Property<int>("PagesDownloaded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pages_downloaded");

                    b.Property<int>("PagesTotal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pages_total");

                    b.Property<string>("QueuedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("queued_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId")
                        .IsUnique();

                    b.HasIndex("QueuedBy");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_queue_status");

                    b.ToTable("download_queue", (string)null);
                });

            modelBuilder.Entity("ArrghServer.Data.Models.ExternalSource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("api_key");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("base_url");

                    b.Property<string>("ContentTypes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_types");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("DefaultExplicit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("default_explicit");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<bool>("IsCommunity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_community");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("SourceKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_key");

                    b.HasKey("Id");

                    b.ToTable("external_sources", (string)null);
                });

            modelBuilder.Entity("ArrghServer.Data.Models.ReadProgress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ChapterId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("chapter_id");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed");

                    b.Property<int>("CurrentPage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_page");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("idx_read_progress_chapter");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_read_progress_user");

                    b.HasIndex("UserId", "ChapterId")
                        .IsUnique();

                    b.ToTable("read_progress", (string)null);
                });

            modelBuilder.Entity("ArrghServer.Data.Models.ServerSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("server_settings", (string)null);
                });

            modelBuilder.Entity("ArrghServer.Data.Models.SyncLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("TitleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title_id");

                    b.HasKey("Id");

                    b.HasIndex("TitleId", "CreatedAt")
                        .HasDatabaseName("idx_sync_log_title_id");

                    b.ToTable("sync_log", (string)null);
                });

            modelBuilder.Entity("ArrghServer.Data.Models.SyncWarning", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("plugin_id");

                    b.Property<string>("TitleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title_id");

                    b.HasKey("Id");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("idx_sync_warnings_title_id");

                    b.HasIndex("TitleId", "PluginId")
                        .IsUnique();

                    b.ToTable("sync_warnings", (string)null);
                });

            modelBuilder.Entity("ArrghServer.Data.Models.Title", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT")
                        .HasColumnName("author");

                    b.Property<bool?>("AutoDownload")
                        .HasColumnType("INTEGER")
                        .HasColumnName("auto_download");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("cover_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DownloadDir")
                        .HasColumnType("TEXT")
                        .HasColumnName("download_dir");

                    b.Property<bool>("IsExplicit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_explicit");

                    b.Property<string>("LocalPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("local_path");

                    b.Property<string>("MangaupdatesId")
                        .HasColumnType("TEXT")
                        .HasColumnName("mangaupdates_id");

                    b.Property<string>("MetadataSource")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_source");

                    b.Property<string>("MetadataSourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_source_id");

                    b.Property<string>("ReaderMode")
                        .HasColumnType("TEXT")
                        .HasColumnName("reader_mode");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sync_status");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("TitleName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("MangaupdatesId")
                        .IsUnique()
                        .HasFilter("mangaupdates_id IS NOT NULL");

                    b.ToTable("titles", (string)null);
                });

            modelBuilder.Entity("ArrghServer.Data.Models.TitleAlias", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<string>("TitleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title_id");

                    b.HasKey("Id");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("idx_title_aliases_title_id");

                    b.ToTable("title_aliases", (string)null);
                });

            modelBuilder.Entity("ArrghServer.Data.Models.TitleMeta", b =>
                {
                    b.Property<string>("TitleKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("title_key");

                    b.Property<int>("ChapterCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chapter_count");

                    b.Property<string>("CoverCdnUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("cover_cdn_url");

                    b.Property<string>("CoverLocalPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("cover_local_path");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("fetched_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_id");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.HasKey("TitleKey");

                    b.ToTable("title_meta", (string)null);
                });

            modelBuilder.Entity("ArrghServer.Data.Models.TitleSource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("discovered_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_id");

                    b.Property<string>("TitleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title_id");

                    b.HasKey("Id");

                    b.HasIndex("TitleId", "Source")
                        .IsUnique();

                    b.ToTable("title_sources", (string)null);
                });

            modelBuilder.Entity("ArrghServer.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("AllowExplicit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("allow_explicit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ArrghServer.Data.Models.UserTitle", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("TitleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("title_id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.HasKey("UserId", "TitleId");

                    b.HasIndex("TitleId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_titles_user");

                    b.ToTable("user_titles", (string)null);
                });

            modelBuilder.Entity("ArrghServer.Data.Models.UserTitleSettings", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("TitleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("title_id");

                    b.Property<string>("ReaderMode")
                        .HasColumnType("TEXT")
                        .HasColumnName("reader_mode");

                    b.HasKey("UserId", "TitleId");

                    b.HasIndex("TitleId");

                    b.ToTable("user_title_settings", (string)null);
                });

            modelBuilder.Entity("ArrghServer.Data.Models.Chapter", b =>
                {
                    b.HasOne("ArrghServer.Data.Models.Title", "Title")
                        .WithMany("Chapters")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("ArrghServer.Data.Models.ChapterSource", b =>
                {
                    b.HasOne("ArrghServer.Data.Models.Chapter", "Chapter")
                        .WithMany("ChapterSources")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("ArrghServer.Data.Models.DownloadQueueItem", b =>
                {
                    b.HasOne("ArrghServer.Data.Models.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArrghServer.Data.Models.User", "QueuedByUser")
                        .WithMany("QueueItems")
                        .HasForeignKey("QueuedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chapter");

                    b.Navigation("QueuedByUser");
                });

            modelBuilder.Entity("ArrghServer.Data.Models.ReadProgress", b =>
                {
                    b.HasOne("ArrghServer.Data.Models.Chapter", "Chapter")
                        .WithMany("ReadProgresses")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArrghServer.Data.Models.User", "User")
                        .WithMany("ReadProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArrghServer.Data.Models.SyncLog", b =>
                {
                    b.HasOne("ArrghServer.Data.Models.Title", "Title")
                        .WithMany("SyncLogs")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("ArrghServer.Data.Models.SyncWarning", b =>
                {
                    b.HasOne("ArrghServer.Data.Models.Title", "Title")
                        .WithMany("SyncWarnings")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("ArrghServer.Data.Models.TitleAlias", b =>
                {
                    b.HasOne("ArrghServer.Data.Models.Title", "Title")
                        .WithMany("TitleAliases")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("ArrghServer.Data.Models.TitleSource", b =>
                {
                    b.HasOne("ArrghServer.Data.Models.Title", "Title")
                        .WithMany("TitleSources")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("ArrghServer.Data.Models.UserTitle", b =>
                {
                    b.HasOne("ArrghServer.Data.Models.Title", "Title")
                        .WithMany("UserTitles")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArrghServer.Data.Models.User", "User")
                        .WithMany("UserTitles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArrghServer.Data.Models.UserTitleSettings", b =>
                {
                    b.HasOne("ArrghServer.Data.Models.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArrghServer.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArrghServer.Data.Models.Chapter", b =>
                {
                    b.Navigation("ChapterSources");

                    b.Navigation("ReadProgresses");
                });

            modelBuilder.Entity("ArrghServer.Data.Models.Title", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("SyncLogs");

                    b.Navigation("SyncWarnings");

                    b.Navigation("TitleAliases");

                    b.Navigation("TitleSources");

                    b.Navigation("UserTitles");
                });

            modelBuilder.Entity("ArrghServer.Data.Models.User", b =>
                {
                    b.Navigation("QueueItems");

                    b.Navigation("ReadProgresses");

                    b.Navigation("UserTitles");
                });
#pragma warning restore 612, 618
        }
    }
}
